name: musa-550-fall-2021
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.1
  - affine=2.3.0
  - aiobotocore=1.4.0
  - aiohttp=3.7.4.post0
  - aioitertools=0.8.0
  - altair=4.1.0
  - anyio=3.3.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - arrow-cpp=4.0.0
  - asciitree=0.3.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.9.3
  - black=21.7b0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.3.3
  - boost-cpp=1.74.0
  - botocore=1.20.106
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bs4=4.9.3
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - cartopy=0.19.0.post1
  - cenpy=1.0.0.post4
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.5.0
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - colorcet=2.0.6
  - contextily=1.1.0
  - cramjam=2.3.1
  - cryptography=3.4.7
  - curl=7.79.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dash=1.21.0
  - dash-core-components=1.17.1
  - dash-html-components=1.1.4
  - dash-renderer=1.9.1
  - dash-table=4.12.0
  - dask=2021.8.1
  - dask-core=2021.8.1
  - dataclasses=0.8
  - datashader=0.13.0
  - datashape=0.5.4
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=4.4.2
  - defusedxml=0.7.1
  - descartes=1.1.0
  - distributed=2021.8.1
  - earthpy=0.9.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.4.1
  - fasteners=0.16
  - fastparquet=0.7.1
  - fiona=1.8.18
  - flask=2.0.1
  - flask-compress=1.10.1
  - folium=0.12.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2021.7.0
  - future=0.18.2
  - fuzzywuzzy=0.18.0
  - gdal=3.2.1
  - geckodriver=0.29.1
  - geographiclib=1.52
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geopy=2.2.0
  - geos=3.9.1
  - geotiff=1.6.0
  - geoviews=1.9.1
  - geoviews-core=1.9.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - glog=0.5.0
  - grpc-cpp=1.37.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.14.5
  - hvplot=0.7.3
  - icu=68.1
  - idna=3.1
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - intake=0.6.3
  - intake-parquet=0.2.3
  - intake-xarray=0.5.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.3
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.9
  - jupyterlab_code_formatter=1.4.10
  - jupyterlab_server=2.8.1
  - jupyterlab_widgets=1.0.2
  - jxrlib=1.1
  - kaggle=1.5.12
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.79.0
  - libcxx=12.0.1
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgdal=3.2.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.68.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.16.0
  - libpysal=4.5.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libthrift=0.14.1
  - libtiff=4.2.0
  - libutf8proc=2.6.1
  - libuv=1.42.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - llvmlite=0.36.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mercantile=1.2.1
  - missingno=0.4.2
  - mistune=0.8.4
  - mock=4.0.3
  - monotonic=1.5
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclassic=0.3.2
  - nbconvert=5.6.1
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf4=1.5.6
  - networkx=2.6.2
  - nltk=3.6.2
  - nodejs=16.6.1
  - notebook=6.4.3
  - nspr=4.30
  - nss=3.69
  - numba=0.53.1
  - numcodecs=0.9.1
  - numexpr=2.7.3
  - numpy=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.7
  - openssl=1.1.1l
  - orc=1.6.7
  - osmnet=0.1.6
  - osmnx=1.1.1
  - packaging=21.0
  - pandana=0.6.1
  - pandas=1.3.2
  - pandocfilters=1.5.0
  - panel=0.12.1
  - param=1.11.1
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - partd=1.2.0
  - pathspec=0.9.0
  - patsy=0.5.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.2.4
  - pixman=0.40.0
  - plotly=5.3.1
  - pooch=1.5.1
  - poppler=0.89.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=7.2.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyarrow=4.0.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyepsg=0.4.0
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.1.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-levenshtein=0.12.2
  - python-slugify=5.0.2
  - python-snappy=0.6.0
  - python_abi=3.8
  - pytz=2021.1
  - pyviz_comms=2.1.0
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.1.1
  - qtpy=1.11.1
  - rasterio=1.2.6
  - rasterstats=0.15.0
  - re2=2021.04.01
  - readline=8.1
  - regex=2021.8.28
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - requests-unixsocket=0.2.0
  - rio-mucho=1.0.0
  - rio-toa=0.3.0
  - rioxarray=0.7.0
  - rtree=0.9.7
  - s3fs=2021.8.0
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - selenium=3.141.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shapely=1.7.1
  - simplejson=3.17.5
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.0.1
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.12.1
  - testpath=0.5.0
  - text-unidecode=1.3
  - textblob=0.15.3
  - threadpoolctl=2.2.0
  - thrift=0.13.0
  - tifffile=2021.4.8
  - tiledb=2.2.9
  - tk=8.6.11
  - tomli=1.2.1
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.1.0
  - tweepy=3.10.0
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzcode=2021a
  - tzdata=2021a
  - unidecode=1.3.2
  - urllib3=1.26.6
  - vega=3.5.0
  - vega_datasets=0.9.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - wordcloud=1.8.1
  - wrapt=1.12.1
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zarr=2.10.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - arcgis2geojson==2.0.1
    - blis==0.7.5
    - carto2gpd==1.0.7
    - catalogue==2.0.6
    - configparser==5.0.2
    - crayons==0.4.0
    - cymem==2.0.6
    - esri2gpd==1.0.7
    - jellyfish==0.6.1
    - jupyter-panel-proxy==0.1.0
    - jupyter-server-proxy==3.1.0
    - langcodes==3.3.0
    - murmurhash==1.0.6
    - osm2gpd==1.0.1
    - pathy==0.6.1
    - preshed==3.0.6
    - pydantic==1.8.2
    - python-dotenv==0.19.2
    - simpervisor==0.4
    - smart-open==5.2.1
    - spacy==3.2.1
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - thinc==8.0.13
    - typer==0.4.0
    - us==2.0.2
    - wasabi==0.9.0
    - webdriver-manager==3.4.2
