name: musa-550-fall-2021
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - backports.functools_lru_cache=1.6.4
  - cartopy=0.19.0.post1
  - cramjam=2.3.1
  - dataclasses=0.8
  - datashader=0.13.0
  - datashape=0.5.4
  - dbus=1.13.6
  - debugpy=1.4.1
  - fiona=1.8.18
  - geographiclib=1.52
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geopy=2.2.0
  - geos=3.9.1
  - geotiff=1.6.0
  - geoviews=1.9.1
  - geoviews-core=1.9.1
  - gettext=0.19.8.1
  - holoviews=1.14.5
  - hvplot=0.7.3
  - icu=68.1
  - idna=3.1
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - intake=0.6.3
  - intake-parquet=0.2.3
  - intake-xarray=0.5.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.3
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.9
  - jupyterlab_code_formatter=1.4.10
  - jupyterlab_server=2.8.1
  - jupyterlab_widgets=1.0.2
  - jxrlib=1.1
  - kaggle=1.5.12
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - mapclassify=2.4.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mercantile=1.2.1
  - missingno=0.4.2
  - mistune=0.8.4
  - mock=4.0.3
  - monotonic=1.5
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclassic=0.3.2
  - nbconvert=5.6.1
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf4=1.5.6
  - networkx=2.6.2
  - nltk=3.6.2
  - nodejs=16.6.1
  - notebook=6.4.3
  - nspr=4.30
  - nss=3.69
  - numba=0.53.1
  - numcodecs=0.9.1
  - numexpr=2.7.3
  - numpy=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.7
  - openssl=1.1.1l
  - orc=1.6.7
  - osmnet=0.1.6
  - osmnx=1.1.1
  - packaging=21.0
  - pandana=0.6.1
  - pandas=1.3.2
  - pandocfilters=1.5.0
  - panel=0.12.1
  - param=1.11.1
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - partd=1.2.0
  - pathspec=0.9.0
  - patsy=0.5.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.2.4
  - pixman=0.40.0
  - plotly=5.3.1
  - pooch=1.5.1
  - poppler=0.89.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=7.2.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyarrow=4.0.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyepsg=0.4.0
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.1.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-levenshtein=0.12.2
  - python-slugify=5.0.2
  - python-snappy=0.6.0
  - python_abi=3.8
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - requests-unixsocket=0.2.0
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - testpath=0.5.0
  - text-unidecode=1.3
  - textblob=0.15.3
  - toolz=0.11.1
  - tzcode=2021a
  - tzdata=2021a
  - unidecode=1.3.2
  - urllib3=1.26.6
  - vega=3.5.0
  - vega_datasets=0.9.0
  - websocket-client=0.57.0
  - widgetsnbextension=3.5.1
  - wordcloud=1.8.1
  - yaml=0.2.5
  - yarl=1.6.3

  - pip:
    - arcgis2geojson==2.0.1
    - blis==0.7.5
    - carto2gpd==1.0.7
    - catalogue==2.0.6
    - configparser==5.0.2
    - crayons==0.4.0
    - cymem==2.0.6
    - esri2gpd==1.0.7
    - jellyfish==0.6.1
    - jupyter-panel-proxy==0.1.0
    - jupyter-server-proxy==3.1.0
    - langcodes==3.3.0
    - murmurhash==1.0.6
    - osm2gpd==1.0.1
    - pathy==0.6.1
    - preshed==3.0.6
    - pydantic==1.8.2
    - python-dotenv==0.19.2
    - simpervisor==0.4
    - smart-open==5.2.1
    - spacy==3.2.1
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - thinc==8.0.13
    - typer==0.4.0
    - us==2.0.2
    - wasabi==0.9.0
    - webdriver-manager==3.4.2
