name: musa-550-final
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.4
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - numpy=1.21.2
  - pandas=1.3.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - osmnet=0.1.6
  - osmnx=1.1.1
  - geoviews=1.9.1
  - geoviews-core=1.9.1
  - hvplot=0.7.3
  - holoviews=1.14.5
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - altair=4.1.0
  - kaggle=1.5.12
  - nltk=3.6.2
  - aioitertools=0.8.0
  - multidict=5.1.0
  - numpy=1.21.2
  - re2=2021.04.01
  - pillow=8.2.0
  - wordcloud=1.8.1
  - ipywidgets=7.6.5

  - pip:
    - osm2gpd==1.0.1
    - spacy==3.2.1
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1